###########################################################
#                  Panda Sandbox(钟馗沙箱)                  #
###########################################################
#
# Sandbox Release Version
version: 1.0.0-alpha

# Panda Variable Setting
variable:
  # The current host localname
  hostname: default
  # The current host manage NIC address
  hostaddr: "192.168.0.1"

# Panda Advanced Setting
advanced:
  ## The running mode of the sandbox to filter file
  ## Single mode: 1
  ## Cluster mode: 2
  mode: 1
  #################### Cluster Mode ###################
  master: yes
  server: 172.16.12.1
  ## Enable creation of memory dump of the analysis machine before shutting
  ## down. Even if turned off, this functionality can also be enabled at
  ## submission. Currently available for: VirtualBox and Libvirt modules (KVM).
  memory_dump: False
  ## To enable the procmon analyser running in the machine.
  procmon_dump: False
  ## The file operations by the malware in the machine.
  dropped_files: True
  ## When the timeout of an analysis is hit, the VM is just killed by default.
  ## For some long-running setups it might be interesting to terminate the
  ## monitored processes before killing the VM so that connections are closed.
  terminate_processes: False
